{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Pizza Putchases",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 15 },
   "targets": [
    { "expr": "Pizzas_Bought_total", "legendFormat": "Pizzas Bought" },
    { "expr": "Purchase_Failures_total", "legendFormat": "Purchase Failures" }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 15 },
   "targets": [
    { "expr": "Request_Latency_milliseconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "CPU_percent", "legendFormat": "CPU %" },
    { "expr": "Memory_percent", "legendFormat": "Memory %" }
   ]
  },
  {
   "title": "Total Revenue",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Revenue_USD_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Auth Requests in Last Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 24 },
   "targets": [
    { "expr": "rate(AuthRequests_total[1m])", "legendFormat": "Successful Auth Requests" },
    {
     "expr": "rate(Failed_AuthRequests_total[$__rate_interval])",
     "legendFormat": "Failed Auth Requests"
    }
   ]
  },
  {
   "title": "HTTP Requests by Method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 24 },
   "targets": [
    { "expr": "requests_total", "legendFormat": "{{method}}" }
   ]
  },
  {
   "title": "Current Users Active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 33 },
   "targets": [
    { "expr": "ActiveUsers_total", "legendFormat": "Active Users" }
   ]
  }
 ]
}